version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_transactions
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=transactions
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/transactions/data
    restart: always


volumes:
  pgdata: